#!/usr/bin/env bash
# Bot telegram
TOKEN_BOT="5060855938:AAGEghPMywY54HWtE3PsO2NxGCqqBgecRqo"
CHAT_ID="1178201791"
HOST=$(cat logremot.txt|grep tunneled|awk '{print $1}')

PESAN="Form server <b>$(hostname)</b> Your link: "
curl -s -X POST "https://api.telegram.org/bot$TOKEN_BOT/sendmessage" -d "chat_id=$CHAT_ID" -d "parse_mode=html" -d "text=$PESAN $HOST"
clear
