#!/usr/bin/env bash
# Bot telegram
TOKEN_BOT="xxx"
CHAT_ID="xxx"
HOST=$(cat logremot.txt|grep tunneled|awk '{print $1}')
PESAN="Form server <b>$(hostname)</b>"
IP=$(curl -s http://tnx.nl/ip)

curl -s -X POST "https://api.telegram.org/bot$TOKEN_BOT/sendmessage" -d "chat_id=$CHAT_ID" -d "parse_mode=html" -d "text=$PESAN%0A $IP%0A $HOST"
clear
